### PR TITLE
Used depth buffer in shader to increase the linear depth resolution t…

### PR DESCRIPTION
**Pull request by trocolit2**
…o float-32

Included test with high resolution depth buffer

### CODE REVIEW

**Comment by doudou** [comment]
is there a good reason to still read the pixel buffer ?

**Comment by trocolit2** [comment]
@doudou Yes.. we need the normal data!
I did not find a way to return normal data without pixel buffer.
I made some tests, and depth data require more resolution than normal data.

**Comment by doudou** [comment]
Are we still using threads in here ?

**Comment by trocolit2** [comment]
Yes, It is needed to wait shader process finish to grab image.
Otherwise, the final image could have an error.

**Comment by doudou** [comment]
> Yes, It is needed to wait shader process finish to grab image.

No it's not _needed_. OSG can be executed synchronously, and it's how it has been done in e.g. the UW camera simulation so far.

I'm asking because _if there is MT_, the MT synchronisation is deeply broken in this class.

**Comment by romulogcerqueira** [comment]
@doudou , should we finish this PR as-is?

**Comment by doudou** [comment]
I guess so, yes.

**Comment by romulogcerqueira** [comment]
:+1:

**Pull request merged**
