### PR TITLE
configure near and far parameters

### PR DESCRIPTION
**Pull request by gustavoneves12**
changed culling mode
changed near and far mode

### CODE REVIEW

**Comment by doudou** [comment]
Please explain _why_ you do things. I can see in the code that you changed the culling mode. What is waaaay more important is WHY.

**Comment by gustavoneves12** [comment]
@doudou I did this changes because I don't want to clip the objects inside the view frustum. To do this, I set this flags to change the culling mode and the "near and far compute" mode.

**Comment by doudou** [comment]
>  I did this changes because I don't want to clip the objects inside the view frustum

I got that. Except that the default culling modes should not cull anything that is being seen.

The near/far computation is fair enough. We probably want to control those. You still don't explain why turning off shadow-occlusion and (more critically) backface culling is a good thing. Removing backface culling is really the killer here.

You say what you want ("I want the scene to look good") but you don't explain why what you did MAKES IT good.

**Comment by doudou** [comment]
Is ImageViewerCaptureTool used in the orogen integration or only for tests ?

**Comment by romulogcerqueira** [comment]
Hi Sylvain,

I am using ImageViewerCaptureTool to set FOV and grab the normal and depth images to use in Sonar Simulation.

**Comment by doudou** [comment]
Then you should _really_ make these parameters configurable. The min/max is basically defined by the sonar you are trying to simulate, and you'll get a lot of performance by reducing the max to the acceptable minimum.

**Comment by Thomio-Watanabe** [comment]
With the last commit the imaging_sonar_simulation package compiles. 
https://github.com/Brazilian-Institute-of-Robotics/simulation-orogen-imaging_sonar_simulation

**Pull request merged**
